name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18', '20']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: yarn install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build

      - name: yarn test
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test
